
import React from 'react';
import { 
  Moon, Heart, CloudRain, ShieldCheck, Users, Zap 
} from 'lucide-react';
import { Category } from './types';

export const CATEGORIES: Category[] = [
  {
    id: 'islamic',
    name: 'Islamic',
    description: 'Faith-based captions, Quranic verses, and spiritual reminders.',
    icon: 'Moon',
    gradient: 'from-emerald-500/20 to-teal-500/20',
    seoTitle: 'Islamic Captions for Instagram & Facebook | AI Powered',
    seoDescription: 'Generate beautiful Islamic captions inspired by Quran and Hadith in Bangla and English.',
    promptGuidance: 'Focus on peace, submission to Allah, gratitude, and prophetic wisdom. Use respectful and spiritual language.'
  },
  {
    id: 'romantic',
    name: 'Romantic',
    description: 'Sweet, passionate, and poetic captions for your loved ones.',
    icon: 'Heart',
    gradient: 'from-rose-500/20 to-pink-500/20',
    seoTitle: 'Best Romantic Captions for Couples | Love Captions AI',
    seoDescription: 'Create heartfelt romantic captions for your partner using AI. Poetic and emotional styles.',
    promptGuidance: 'Focus on intimacy, soul connection, devotion, and beauty. Use warm and affectionate imagery.'
  },
  {
    id: 'sad',
    name: 'Sad & Deep',
    description: 'Reflective and emotional captions for heartbreaks and lonely nights.',
    icon: 'CloudRain',
    gradient: 'from-blue-500/20 to-indigo-500/20',
    seoTitle: 'Sad Captions for Instagram | Deep & Emotional AI Captions',
    seoDescription: 'Express your feelings with deep and meaningful sad captions generated by AI.',
    promptGuidance: 'Focus on melancholy, resilience, inner growth, and the beauty of healing. Avoid overly negative tone.'
  },
  {
    id: 'attitude',
    name: 'Attitude',
    description: 'Bold, sassy, and confident captions to show your personality.',
    icon: 'ShieldCheck',
    gradient: 'from-orange-500/20 to-amber-500/20',
    seoTitle: 'Attitude Captions for Boys & Girls | Cool AI Captions',
    seoDescription: 'Generate bold attitude captions that define your personality and confidence.',
    promptGuidance: 'Focus on self-respect, ambition, dominance, and wit. Keep it sharp and impactful.'
  },
  {
    id: 'friendship',
    name: 'Friendship',
    description: 'Celebratory and fun captions for your best friends and squad.',
    icon: 'Users',
    gradient: 'from-yellow-500/20 to-lime-500/20',
    seoTitle: 'Friendship Captions for Besties | AI Squad Captions',
    seoDescription: 'Celebrate your bonds with creative friendship captions for your social media posts.',
    promptGuidance: 'Focus on loyalty, shared memories, laughter, and brotherhood/sisterhood.'
  },
  {
    id: 'motivational',
    name: 'Motivational',
    description: 'Empowering quotes and captions to fuel your hustle.',
    icon: 'Zap',
    gradient: 'from-purple-500/20 to-violet-500/20',
    seoTitle: 'Daily Motivational Captions | Hustle & Success AI Quotes',
    seoDescription: 'Get inspired with powerful motivational captions and success quotes generated by AI.',
    promptGuidance: 'Focus on perseverance, grit, vision, and breaking limits. Use active and energetic language.'
  }
];

export const TONES = [
  { value: 'short', label: 'Short & Snappy' },
  { value: 'long', label: 'Long & Storytelling' },
  { value: 'emotional', label: 'Heartfelt & Emotional' },
  { value: 'deep', label: 'Deep & Philosophical' },
  { value: 'poetic', label: 'Poetic & Aesthetic' },
  { value: 'modern', label: 'Modern & Gen-Z' }
];

export const LANGUAGES = [
  { value: 'english', label: 'English' },
  { value: 'bangla', label: 'Bangla' },
  { value: 'banglish', label: 'Banglish (Bangla words in English letters)' }
];
